name: GitHub Metrics
on:
  schedule:
    - cron:  '0 0 * * *'
    - cron:  '0 12 * * *'
  push:
    branches:
      - 'master'
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: "metrics"
  cancel-in-progress: true
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: profile-metrics
    steps:
      - name: Configure Git Credentials
        shell: bash
        env:
          username: ${{ github.repository_owner }}
          email: TheWisker@protonmail.com
          repo_name: ${{ github.event.repository.name }}
        run: |
          git config --global user.name $username
          git config --global user.email $email
          git config --global init.defaultBranch master
          git config --global --add safe.directory /__w/$repo_name/$repo_name
          
          echo "Configured Git Credentials"
    
      - name: Base Metrics
        uses: TheWisker/StaticMetrics@master
        with:
          base: header, activity, community, repositories, metadata
          token: ${{ secrets.METRICS_TOKEN }}
          repositories_affiliations: owner, collaborator, organization_member
          user: ${{ github.repository_owner }}
          filename: base.*
          output_action: none
          output_condition: data-changed
          optimize: css, xml, svg
          config_display: columns
          config_animations: yes
          config_base64: yes
          config_output: svg
          retries: 5
          retries_delay: 600
          retries_output_action: 5
          retries_delay_output_action: 300
          notice_releases: yes
          use_prebuilt_image: yes
          experimental_features: --optimize-svg
    
      - name: Introduction Metrics
        uses: TheWisker/StaticMetrics@master
        with:
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          repositories_affiliations: owner, collaborator, organization_member
          plugin_introduction: yes
          plugin_introduction_title: Introduction
          user: ${{ github.repository_owner }}
          filename: introduction.*
          output_action: none
          output_condition: data-changed
          optimize: css, xml, svg
          config_display: columns
          config_animations: yes
          config_base64: yes
          config_output: svg
          retries: 5
          retries_delay: 600
          retries_output_action: 5
          retries_delay_output_action: 300
          notice_releases: yes
          use_prebuilt_image: yes
          experimental_features: --optimize-svg
          
      - name: Language Metrics
        uses: TheWisker/StaticMetrics@master
        with:
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          repositories_affiliations: owner, collaborator, organization_member
          plugin_languages: yes
          plugin_languages_limit: 0
          plugin_languages_details: percentage, lines
          plugin_languages_indepth: yes
          user: ${{ github.repository_owner }}
          filename: language.*
          output_action: none
          output_condition: data-changed
          optimize: css, xml, svg
          config_display: columns
          config_animations: yes
          config_base64: yes
          config_output: svg
          retries: 5
          retries_delay: 600
          retries_output_action: 5
          retries_delay_output_action: 300
          notice_releases: yes
          use_prebuilt_image: yes
          experimental_features: --optimize-svg
          
      - name: Habits Metrics
        uses: TheWisker/StaticMetrics@master
        with:
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          repositories_affiliations: owner, collaborator, organization_member
          plugin_habits: yes
          plugin_habits_from: 500
          plugin_habits_days: 21
          plugin_habits_facts: yes
          plugin_habits_languages_limit: 0
          user: ${{ github.repository_owner }}
          filename: habits.*
          output_action: none
          output_condition: data-changed
          optimize: css, xml, svg
          config_display: columns
          config_animations: yes
          config_base64: yes
          config_output: svg
          retries: 5
          retries_delay: 600
          retries_output_action: 5
          retries_delay_output_action: 300
          notice_releases: yes
          use_prebuilt_image: yes
          experimental_features: --optimize-svg
          
      - name: Traffic Metrics
        uses: TheWisker/StaticMetrics@master
        with:
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          repositories_affiliations: owner, collaborator, organization_member
          plugin_traffic: yes
          user: ${{ github.repository_owner }}
          filename: traffic.*
          output_action: none
          output_condition: data-changed
          optimize: css, xml, svg
          config_display: columns
          config_animations: yes
          config_base64: yes
          config_output: svg
          retries: 5
          retries_delay: 600
          retries_output_action: 5
          retries_delay_output_action: 300
          notice_releases: yes
          use_prebuilt_image: yes
          experimental_features: --optimize-svg
          
      - name: Licenses Metrics
        uses: TheWisker/StaticMetrics@master
        with:
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          repositories_affiliations: owner, collaborator, organization_member
          plugin_licenses: yes
          plugin_licenses_legal: yes
          user: ${{ github.repository_owner }}
          filename: licenses.*
          output_action: none
          output_condition: data-changed
          optimize: css, xml, svg
          config_display: columns
          config_animations: yes
          config_base64: yes
          config_output: svg
          retries: 5
          retries_delay: 600
          retries_output_action: 5
          retries_delay_output_action: 300
          notice_releases: yes
          use_prebuilt_image: yes
          experimental_features: --optimize-svg

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Flush Metrics
        shell: bash
        run: |
          mkdir -p ./assets/metrics
          cp -f /metrics_renders/* ./assets/metrics
          
          echo "Flushed Metrics"

      - name: Update Repository
        shell: bash
        run: |
          git add .
          git commit -m "Metrics Update"
          git push
          
          echo "Updated Repository"
