name: GitHub Metrics
on:
  schedule:
    - cron:  '0 0 * * *'
    - cron:  '0 12 * * *'
  push:
    branches:
      - 'master'
  workflow_dispatch:
concurrency:
  group: "metrics"
  cancel-in-progress: true
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: profile-metrics
    steps:
      - uses: TheWisker/StaticMetrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          base: header, activity, community, repositories, metadata
          repositories_affiliations: owner, collaborator, organization_member
          
          plugin_introduction: yes
          plugin_introduction_title: Introduction
          
          plugin_languages: yes
          plugin_languages_limit: 0
          plugin_languages_details: percentage, lines
          plugin_languages_indepth: yes
          
          plugin_habits: yes
          plugin_habits_from: 500
          plugin_habits_days: 21
          plugin_habits_facts: yes
          plugin_habits_languages_limit: 0
          
          plugin_traffic: yes
          
          plugin_licenses: yes
          plugin_licenses_legal: yes
          
          user: ${{ github.repository_owner }}
          committer_branch: master
          committer_message: Metrics added ${filename}
          filename: assets/${{ github.repository_owner }}-metrics.*
          output_action: commit
          output_condition: data-changed
          optimize: css, xml, svg
          config_twemoji: no
          config_gemoji: yes
          config_octicon: no
          config_display: columns
          config_animations: yes
          config_base64: yes
          config_output: svg
          retries: 5
          retries_delay: 600
          retries_output_action: 5
          retries_delay_output_action: 300
          notice_releases: yes
          use_prebuilt_image: yes
          experimental_features: --optimize-svg
